# These are supported funding model platforms

#github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: dreamnet # Replace with a single Patreon username
ko_fi: dreamnet # Replace with a single Ko-fi username
custom: ['https://commerce.coinbase.com/checkout/24a8bcb6-22db-4166-9bea-fb24fe78f1cd'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
